on:
  push:
    branches:
      - main

jobs:
  push:
    name: 'Deploy'
    uses: ./.github/workflows/template.yaml
    secrets: inherit
    with:
      ENV: prod
      REGISTRY: ghcr.io/${{ github.repository_owner }}
      IMAGE_NAME: untangled-tunnel
